package Metier;
// Generated 22 juin 2013 13:35:50 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Long idArticle;
     private Fournisseur fournisseur;
     private ClasseArticle classeArticle;
     private User user;
     private String numSerie;
     private String marque;
     private String modele;
     private Date dateLivraison;
     private String notes;

    public Article() {
    }

	
    public Article(Fournisseur fournisseur, ClasseArticle classeArticle) {
        this.fournisseur = fournisseur;
        this.classeArticle = classeArticle;
    }
    public Article(Fournisseur fournisseur, ClasseArticle classeArticle, User user, String numSerie, String marque, String modele, Date dateLivraison, String notes) {
       this.fournisseur = fournisseur;
       this.classeArticle = classeArticle;
       this.user = user;
       this.numSerie = numSerie;
       this.marque = marque;
       this.modele = modele;
       this.dateLivraison = dateLivraison;
       this.notes = notes;
    }
   
    public Long getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Long idArticle) {
        this.idArticle = idArticle;
    }
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    public ClasseArticle getClasseArticle() {
        return this.classeArticle;
    }
    
    public void setClasseArticle(ClasseArticle classeArticle) {
        this.classeArticle = classeArticle;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public String getModele() {
        return this.modele;
    }
    
    public void setModele(String modele) {
        this.modele = modele;
    }
    public Date getDateLivraison() {
        return this.dateLivraison;
    }
    
    public void setDateLivraison(Date dateLivraison) {
        this.dateLivraison = dateLivraison;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


