package Metier;
// Generated 22 juin 2013 13:35:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ClasseArticle generated by hbm2java
 */
public class ClasseArticle  implements java.io.Serializable {


     private Long idClasse;
     private String nomClasse;
     private int quantite;
     private Set demandeArticles = new HashSet(0);
     private Set articles = new HashSet(0);
     private Set demandeArticles_1 = new HashSet(0);
     private Set articles_1 = new HashSet(0);

    public ClasseArticle() {
    }

	
    public ClasseArticle(int quantite) {
        this.quantite = quantite;
    }
    public ClasseArticle(String nomClasse, int quantite, Set demandeArticles, Set articles, Set demandeArticles_1, Set articles_1) {
       this.nomClasse = nomClasse;
       this.quantite = quantite;
       this.demandeArticles = demandeArticles;
       this.articles = articles;
       this.demandeArticles_1 = demandeArticles_1;
       this.articles_1 = articles_1;
    }
   
    public Long getIdClasse() {
        return this.idClasse;
    }
    
    public void setIdClasse(Long idClasse) {
        this.idClasse = idClasse;
    }
    public String getNomClasse() {
        return this.nomClasse;
    }
    
    public void setNomClasse(String nomClasse) {
        this.nomClasse = nomClasse;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }
    public Set getDemandeArticles() {
        return this.demandeArticles;
    }
    
    public void setDemandeArticles(Set demandeArticles) {
        this.demandeArticles = demandeArticles;
    }
    public Set getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set articles) {
        this.articles = articles;
    }
    public Set getDemandeArticles_1() {
        return this.demandeArticles_1;
    }
    
    public void setDemandeArticles_1(Set demandeArticles_1) {
        this.demandeArticles_1 = demandeArticles_1;
    }
    public Set getArticles_1() {
        return this.articles_1;
    }
    
    public void setArticles_1(Set articles_1) {
        this.articles_1 = articles_1;
    }




}


