package Metier;
// Generated 22 juin 2013 13:35:50 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Long idMsg;
     private User user;
     private String msgTo;
     private Date dateMsg;
     private String objetMsg;
     private String msg;
     private boolean msgVue;

    public Message() {
    }

	
    public Message(User user, boolean msgVue) {
        this.user = user;
        this.msgVue = msgVue;
    }
    public Message(User user, String msgTo, Date dateMsg, String objetMsg, String msg, boolean msgVue) {
       this.user = user;
       this.msgTo = msgTo;
       this.dateMsg = dateMsg;
       this.objetMsg = objetMsg;
       this.msg = msg;
       this.msgVue = msgVue;
    }
   
    public Long getIdMsg() {
        return this.idMsg;
    }
    
    public void setIdMsg(Long idMsg) {
        this.idMsg = idMsg;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMsgTo() {
        return this.msgTo;
    }
    
    public void setMsgTo(String msgTo) {
        this.msgTo = msgTo;
    }
    public Date getDateMsg() {
        return this.dateMsg;
    }
    
    public void setDateMsg(Date dateMsg) {
        this.dateMsg = dateMsg;
    }
    public String getObjetMsg() {
        return this.objetMsg;
    }
    
    public void setObjetMsg(String objetMsg) {
        this.objetMsg = objetMsg;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public boolean isMsgVue() {
        return this.msgVue;
    }
    
    public void setMsgVue(boolean msgVue) {
        this.msgVue = msgVue;
    }




}


